version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres:12-alpine
    environment:
    - POSTGRES_DB=simple_bank
    - POSTGRES_USER=root
    - POSTGRES_PASSWORD=root
    ports:
    - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d simple_bank"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - db_data:/var/lib/postgresql/data
  simplebank:
    container_name: simplebank
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    environment:
    - DB_SOURCE=postgres://root:root@postgres:5432/simple_bank?sslmode=disable
    depends_on: # https://github.com/compose-spec/compose-spec/blob/master/schema/compose-spec.json#L178-L198
      postgres:
        condition: service_healthy
    command:
    - /app/main

volumes:
  db_data: